kind: pipeline
type: docker
name: default

steps:
  - name: docker build
    image: plugins/docker
    settings:
      registry: registry.djm.me
      username: droneci
      password:
        from_secret: registry_password
      repo: registry.djm.me/djm.me
      cache_from: registry.djm.me/djm.me:latest
      tags: [latest, "${DRONE_COMMIT}"]

  - name: deploy
    image: docker/compose:1.29.2
    environment:
      APP_ENV: "${DRONE_DEPLOY_TO:-production}"
      COMPOSE_PROJECT_NAME: djm.me
      DOMAIN: djm.me
      REGISTRY_PASSWORD:
        from_secret: registry_password
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    commands:
      - echo $REGISTRY_PASSWORD | docker login -u droneci --password-stdin registry.djm.me
      - docker-compose up -d

# Note: This requires the project to be marked as Trusted in Drone CI
volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
