kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

steps:
  - name: deploy
    image: appleboy/drone-git-push
    settings:
      remote: ssh://dave@summer.djm.me//home/www/djm.me/repo
      ssh_key:
        from_secret: ssh_private_key
      branch: ${DRONE_COMMIT_BRANCH}
      force: true
